# Generated by Django 2.1.3 on 2019-05-07 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnoyingManager', '0002_auto_20190507_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.IntegerField(blank=True, default=1557252533),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_frequency',
            field=models.FloatField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='text_frequency',
            field=models.FloatField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
