# Generated by Django 2.1.4 on 2019-05-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnoyingManager', '0003_auto_20190507_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_frequency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='text_frequency',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.IntegerField(blank=True, default=1557334301),
        ),
    ]
